services:
  frontend:
    build:
      context: ./Everyday-Elegance
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./Ecom-Backend
    ports:
      - "1337:1337"
    volumes:
      - strapi-app-data:/app
      - strapi-uploads:/app/public/uploads
    env_file:
      - ./Ecom-Backend/.env
    environment:
      NODE_ENV: development
    networks:
      - app-network

volumes:
  strapi-app-data:
  strapi-uploads:

networks:
  app-network:
    driver: bridge